version: "3.8"
services:
  postgres_alone:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: Yatathakar123!
      POSTGRES_USER: qj
      POSTGRES_DB: qj_roots
      PGDATA: pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/qj:z
      - ./quran-simple.sql:/docker-entrypoint-initdb.d/quran-simple.sql:z
      - ./root_tables.sql:/docker-entrypoint-initdb.d/root_tables.sql:z
    ports:
      - "5434:5432"
    networks:
      - default